"""Stage 3: structured rules -> clingo source.

Purely mechanical. No language model is involved and no judgement is exercised here, which
is deliberate: every interpretive decision has already been made and reviewed by the time
a rule reaches this module, so the generated logic program is a faithful transcription of
``rules.jsonl`` and nothing else.

Generated files are disposable. The hand-written ontology under ``ontology/`` is not, and
is never written to by this stage.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from .models import Clause, Rule

HEADER = """\
% GENERATED by eiguide compile -- do not edit.
% Source: {doc} {version}, chapter {chapter}
% Regenerate with: uv run eiguide compile --chapter {chapter}
"""

# ASP constants must start lowercase and hold only word characters.
_SAFE = re.compile(r"[^a-z0-9_]")


def asp_constant(name: str) -> str:
    """Coerce an observable name into a legal ASP constant."""
    slug = _SAFE.sub("_", name.strip().lower()).strip("_")
    slug = re.sub(r"_+", "_", slug)
    if not slug:
        slug = "obs"
    if not slug[0].isalpha():
        slug = f"o_{slug}"
    return slug


def quote(text: str) -> str:
    """Quote a string for use as an ASP term."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _body(literals: Iterable[str]) -> str:
    return ", ".join(literals)


def compile_rule(rule: Rule, clause: Clause | None = None) -> str:
    """Render one structured rule as clingo source.

    Emits four things: when the requirement is in force, what observations settle it, and
    the conditions under which it is satisfied or violated. Everything else -- the
    three-valued verdict, the evidence gaps, the capture plan -- follows from ``core.lp``.
    """
    rid = quote(rule.id)
    subject = rule.subject_term
    lines: list[str] = []

    if clause is not None:
        excerpt = clause.text if len(clause.text) <= 160 else clause.text[:157] + "..."
        lines.append(f"% {rule.id} [{clause.page_label}] {excerpt}")
    if rule.notes:
        lines.append(f"% note: {rule.notes}")

    if rule.kind != "obligation":
        # An exemption imposes no duty of its own; it narrows one stated elsewhere, and is
        # realized as a guard in that rule's applicability. Recording it here keeps it
        # traceable instead of vanishing from the compiled output entirely.
        target = ", ".join(rule.modifies) or "(unlinked)"
        lines.append(f"% {rule.kind}: narrows {target}; realized as a guard in that rule's body")
        return "\n".join(lines) + "\n"

    body = list(rule.applicability) or [subject]
    lines.append(f"applies({rid}, {subject}) :- {_body(body)}.")

    if not rule.field_verifiable:
        # A process or paperwork obligation is still recorded and still applies, but no
        # capture can settle it. Emitting no observables keeps it permanently undetermined
        # and visible, rather than silently absent or falsely reported clean.
        lines.append(f"% not field-verifiable ({rule.verifiability}); no observables emitted")
        return "\n".join(lines) + "\n"

    names = [asp_constant(o.name) for o in rule.observables]
    for obs, name in zip(rule.observables, names):
        lines.append(f"requires_obs({rid}, {subject}, {name}) :- applies({rid}, {subject}).")
        lines.append(f"obs_kind({name}, {asp_constant(obs.kind)}).")

    if names:
        # Satisfied only when every observable came back true: a requirement is not
        # partially met.
        checks = ", ".join(f"obs({subject}, {n}, true)" for n in names)
        lines.append(f"satisfied({rid}, {subject}) :- applies({rid}, {subject}), {checks}.")
        # A single false observation is enough to violate it.
        for name in names:
            lines.append(
                f"violated({rid}, {subject}) :- applies({rid}, {subject}), "
                f"obs({subject}, {name}, false)."
            )

    return "\n".join(lines) + "\n"


def check_exemptions(rules: list[Rule]) -> list[str]:
    """Verify every exemption is actually realized in the rule it claims to narrow.

    An exemption carries ``modifies: ["D.6.7"]`` and is implemented as a guard in that
    rule's applicability. Nothing enforces the link, so editing D.6.7 and dropping the
    guard would silently reinstate an obligation the standard waives -- sending an
    inspector after evidence that is explicitly not required, with no test failing.

    The check is deliberately loose: it looks for the exemption's distinguishing predicate
    appearing negated in the target's body, rather than demanding an exact string, so
    rewording a guard does not produce a false alarm.
    """
    by_id = {r.id: r for r in rules}
    problems: list[str] = []
    for rule in rules:
        if rule.kind != "exemption":
            continue
        if not rule.modifies:
            problems.append(f"{rule.id}: exemption names no rule it narrows")
            continue
        # The predicate that distinguishes the exempt population, e.g. internal_to_rack.
        markers = {
            lit.split("(")[0].strip()
            for lit in rule.applicability
            if "(" in lit and not lit.startswith("not ")
        }
        for target_id in rule.modifies:
            target = by_id.get(target_id)
            if target is None:
                problems.append(f"{rule.id}: narrows unknown rule {target_id}")
                continue
            negated = " ".join(lit for lit in target.applicability if lit.startswith("not "))
            if not any(marker in negated for marker in markers):
                problems.append(
                    f"{rule.id} exempts {sorted(markers)} but {target_id} has no matching "
                    f"guard -- the exemption is not in force"
                )
    return problems


def compile_rules(
    rules: list[Rule], clauses: dict[str, Clause], chapter: str, doc: str, version: str
) -> str:
    """Render every rule for a chapter into a single logic program."""
    out = [HEADER.format(doc=doc, version=version, chapter=chapter), ""]
    skipped = 0
    for rule in sorted(rules, key=_sort_key):
        if not rule.reviewed:
            # Unreviewed rules are compiled but flagged, so a solver run can never quietly
            # depend on an interpretation no human has checked.
            out.append(f"% UNREVIEWED -- {rule.id}")
        out.append(compile_rule(rule, clauses.get(rule.clause_id)))
        if not rule.field_verifiable:
            skipped += 1
    out.append(f"% {len(rules)} rules compiled; {skipped} not field-verifiable\n")
    return "\n".join(out)


def _sort_key(rule: Rule) -> tuple:
    parts = rule.id.split(".")
    nums = []
    for p in parts[1:]:
        nums.append(int(p) if p.isdigit() else 0)
    return (parts[0], *nums)
